//! AUTO-GENERATED by `nockup-graft codegen harness-methods`.
//! Source: hoon/lib/harness-bindings.toml sha256:7660c4bf6dcf8784b477fe17b198430808f7158e1a8d38f57963c7635df8b017
//! Re-run after every harness-bindings change. Do not edit by hand.
//!
//! See `tools/graft-inject/src/harness_bindings.rs` for the sidecar
//! schema and `tools/graft-inject/src/codegen.rs` for the emitter.

#![allow(unused_imports)]

use nock_noun_rs::NounSlab;
use vesl_core::Tip5Hash;
use vesl_core::ValidateRule;

/// Typed outcome for `batch-graft` pokes.
///
/// Decoded by [`PokeOutcome::as_batch_outcome`] (see [`BatchOutcomeExt`]).
/// Use to pattern-match on the specific rejection variant the
/// kernel produced — `Error { msg }` for the generic cord-typed
/// kernel error, named struct variants for typed rejections,
/// `Denied { reason }` for gate-clean-deny.
#[derive(Debug)]
pub enum BatchOutcome {
    /// Kernel accepted the poke. `effect_tags` are the head
    /// tags of every emitted effect — typically a single
    /// `*-accepted` or graft-specific success tag.
    Accepted { effect_tags: Vec<String> },
    /// `[%<graft>-error msg=@t]` — cord-typed kernel error.
    Error { msg: String },
    /// Kernel emitted no effects (collapses to
    /// `RejectionReason::Unknown`) or an RBAC pre-check denied
    /// the poke before it reached the kernel.
    Unknown,
    /// Driver-level failure (timeout, NockAppError, protocol
    /// violation). Mirrors `PokeOutcome::Crashed`.
    Crashed,
}

/// Extension trait — decodes a [`vesl_core::PokeOutcome`] into a
/// typed [`BatchOutcome`] when the underlying effect came from
/// `batch-graft`. Other grafts' effects collapse to
/// [`BatchOutcome::Unknown`].
pub trait BatchOutcomeExt {
    fn as_batch_outcome(&self) -> BatchOutcome;
}

impl BatchOutcomeExt for vesl_core::PokeOutcome {
    fn as_batch_outcome(&self) -> BatchOutcome {
        match self {
            vesl_core::PokeOutcome::Accepted { effects } => {
                BatchOutcome::Accepted {
                    effect_tags: vesl_core::effect_head_tags(effects),
                }
            }
            vesl_core::PokeOutcome::Rejected {
                reason: vesl_core::RejectionReason::KernelError { cord, .. },
            } if cord.starts_with("batch-graft:") => {
                BatchOutcome::Error { msg: cord.clone() }
            }
            vesl_core::PokeOutcome::Rejected {
                reason: vesl_core::RejectionReason::Unknown
                    | vesl_core::RejectionReason::RbacDenied { .. },
            } => BatchOutcome::Unknown,
            vesl_core::PokeOutcome::Crashed { .. } => BatchOutcome::Crashed,
            _ => BatchOutcome::Unknown,
        }
    }
}

/// Typed outcome for `clock-graft` pokes.
///
/// Decoded by [`PokeOutcome::as_clock_outcome`] (see [`ClockOutcomeExt`]).
/// Use to pattern-match on the specific rejection variant the
/// kernel produced — `Error { msg }` for the generic cord-typed
/// kernel error, named struct variants for typed rejections,
/// `Denied { reason }` for gate-clean-deny.
#[derive(Debug)]
pub enum ClockOutcome {
    /// Kernel accepted the poke. `effect_tags` are the head
    /// tags of every emitted effect — typically a single
    /// `*-accepted` or graft-specific success tag.
    Accepted { effect_tags: Vec<String> },
    /// `[%<graft>-error msg=@t]` — cord-typed kernel error.
    Error { msg: String },
    /// Kernel emitted no effects (collapses to
    /// `RejectionReason::Unknown`) or an RBAC pre-check denied
    /// the poke before it reached the kernel.
    Unknown,
    /// Driver-level failure (timeout, NockAppError, protocol
    /// violation). Mirrors `PokeOutcome::Crashed`.
    Crashed,
}

/// Extension trait — decodes a [`vesl_core::PokeOutcome`] into a
/// typed [`ClockOutcome`] when the underlying effect came from
/// `clock-graft`. Other grafts' effects collapse to
/// [`ClockOutcome::Unknown`].
pub trait ClockOutcomeExt {
    fn as_clock_outcome(&self) -> ClockOutcome;
}

impl ClockOutcomeExt for vesl_core::PokeOutcome {
    fn as_clock_outcome(&self) -> ClockOutcome {
        match self {
            vesl_core::PokeOutcome::Accepted { effects } => {
                ClockOutcome::Accepted {
                    effect_tags: vesl_core::effect_head_tags(effects),
                }
            }
            vesl_core::PokeOutcome::Rejected {
                reason: vesl_core::RejectionReason::KernelError { cord, .. },
            } if cord.starts_with("clock-graft:") => {
                ClockOutcome::Error { msg: cord.clone() }
            }
            vesl_core::PokeOutcome::Rejected {
                reason: vesl_core::RejectionReason::Unknown
                    | vesl_core::RejectionReason::RbacDenied { .. },
            } => ClockOutcome::Unknown,
            vesl_core::PokeOutcome::Crashed { .. } => ClockOutcome::Crashed,
            _ => ClockOutcome::Unknown,
        }
    }
}

/// Typed outcome for `counter-graft` pokes.
///
/// Decoded by [`PokeOutcome::as_counter_outcome`] (see [`CounterOutcomeExt`]).
/// Use to pattern-match on the specific rejection variant the
/// kernel produced — `Error { msg }` for the generic cord-typed
/// kernel error, named struct variants for typed rejections,
/// `Denied { reason }` for gate-clean-deny.
#[derive(Debug)]
pub enum CounterOutcome {
    /// Kernel accepted the poke. `effect_tags` are the head
    /// tags of every emitted effect — typically a single
    /// `*-accepted` or graft-specific success tag.
    Accepted { effect_tags: Vec<String> },
    /// `[%<graft>-error msg=@t]` — cord-typed kernel error.
    Error { msg: String },
    /// Kernel emitted no effects (collapses to
    /// `RejectionReason::Unknown`) or an RBAC pre-check denied
    /// the poke before it reached the kernel.
    Unknown,
    /// Driver-level failure (timeout, NockAppError, protocol
    /// violation). Mirrors `PokeOutcome::Crashed`.
    Crashed,
}

/// Extension trait — decodes a [`vesl_core::PokeOutcome`] into a
/// typed [`CounterOutcome`] when the underlying effect came from
/// `counter-graft`. Other grafts' effects collapse to
/// [`CounterOutcome::Unknown`].
pub trait CounterOutcomeExt {
    fn as_counter_outcome(&self) -> CounterOutcome;
}

impl CounterOutcomeExt for vesl_core::PokeOutcome {
    fn as_counter_outcome(&self) -> CounterOutcome {
        match self {
            vesl_core::PokeOutcome::Accepted { effects } => {
                CounterOutcome::Accepted {
                    effect_tags: vesl_core::effect_head_tags(effects),
                }
            }
            vesl_core::PokeOutcome::Rejected {
                reason: vesl_core::RejectionReason::KernelError { cord, .. },
            } if cord.starts_with("counter-graft:") => {
                CounterOutcome::Error { msg: cord.clone() }
            }
            vesl_core::PokeOutcome::Rejected {
                reason: vesl_core::RejectionReason::Unknown
                    | vesl_core::RejectionReason::RbacDenied { .. },
            } => CounterOutcome::Unknown,
            vesl_core::PokeOutcome::Crashed { .. } => CounterOutcome::Crashed,
            _ => CounterOutcome::Unknown,
        }
    }
}

/// Typed outcome for `forge-graft` pokes.
///
/// Decoded by [`PokeOutcome::as_forge_outcome`] (see [`ForgeOutcomeExt`]).
/// Use to pattern-match on the specific rejection variant the
/// kernel produced — `Error { msg }` for the generic cord-typed
/// kernel error, named struct variants for typed rejections,
/// `Denied { reason }` for gate-clean-deny.
#[derive(Debug)]
pub enum ForgeOutcome {
    /// Kernel accepted the poke. `effect_tags` are the head
    /// tags of every emitted effect — typically a single
    /// `*-accepted` or graft-specific success tag.
    Accepted { effect_tags: Vec<String> },
    /// `[%<graft>-error msg=@t]` — cord-typed kernel error.
    Error { msg: String },
    /// Kernel emitted no effects (collapses to
    /// `RejectionReason::Unknown`) or an RBAC pre-check denied
    /// the poke before it reached the kernel.
    Unknown,
    /// Driver-level failure (timeout, NockAppError, protocol
    /// violation). Mirrors `PokeOutcome::Crashed`.
    Crashed,
}

/// Extension trait — decodes a [`vesl_core::PokeOutcome`] into a
/// typed [`ForgeOutcome`] when the underlying effect came from
/// `forge-graft`. Other grafts' effects collapse to
/// [`ForgeOutcome::Unknown`].
pub trait ForgeOutcomeExt {
    fn as_forge_outcome(&self) -> ForgeOutcome;
}

impl ForgeOutcomeExt for vesl_core::PokeOutcome {
    fn as_forge_outcome(&self) -> ForgeOutcome {
        match self {
            vesl_core::PokeOutcome::Accepted { effects } => {
                ForgeOutcome::Accepted {
                    effect_tags: vesl_core::effect_head_tags(effects),
                }
            }
            vesl_core::PokeOutcome::Rejected {
                reason: vesl_core::RejectionReason::KernelError { cord, .. },
            } if cord.starts_with("forge-graft:") => {
                ForgeOutcome::Error { msg: cord.clone() }
            }
            vesl_core::PokeOutcome::Rejected {
                reason: vesl_core::RejectionReason::Unknown
                    | vesl_core::RejectionReason::RbacDenied { .. },
            } => ForgeOutcome::Unknown,
            vesl_core::PokeOutcome::Crashed { .. } => ForgeOutcome::Crashed,
            _ => ForgeOutcome::Unknown,
        }
    }
}

/// Typed outcome for `guard-graft` pokes.
///
/// Decoded by [`PokeOutcome::as_guard_outcome`] (see [`GuardOutcomeExt`]).
/// Use to pattern-match on the specific rejection variant the
/// kernel produced — `Error { msg }` for the generic cord-typed
/// kernel error, named struct variants for typed rejections,
/// `Denied { reason }` for gate-clean-deny.
#[derive(Debug)]
pub enum GuardOutcome {
    /// Kernel accepted the poke. `effect_tags` are the head
    /// tags of every emitted effect — typically a single
    /// `*-accepted` or graft-specific success tag.
    Accepted { effect_tags: Vec<String> },
    /// `[%<graft>-error msg=@t]` — cord-typed kernel error.
    Error { msg: String },
    /// Kernel emitted no effects (collapses to
    /// `RejectionReason::Unknown`) or an RBAC pre-check denied
    /// the poke before it reached the kernel.
    Unknown,
    /// Driver-level failure (timeout, NockAppError, protocol
    /// violation). Mirrors `PokeOutcome::Crashed`.
    Crashed,
}

/// Extension trait — decodes a [`vesl_core::PokeOutcome`] into a
/// typed [`GuardOutcome`] when the underlying effect came from
/// `guard-graft`. Other grafts' effects collapse to
/// [`GuardOutcome::Unknown`].
pub trait GuardOutcomeExt {
    fn as_guard_outcome(&self) -> GuardOutcome;
}

impl GuardOutcomeExt for vesl_core::PokeOutcome {
    fn as_guard_outcome(&self) -> GuardOutcome {
        match self {
            vesl_core::PokeOutcome::Accepted { effects } => {
                GuardOutcome::Accepted {
                    effect_tags: vesl_core::effect_head_tags(effects),
                }
            }
            vesl_core::PokeOutcome::Rejected {
                reason: vesl_core::RejectionReason::KernelError { cord, .. },
            } if cord.starts_with("guard-graft:") => {
                GuardOutcome::Error { msg: cord.clone() }
            }
            vesl_core::PokeOutcome::Rejected {
                reason: vesl_core::RejectionReason::Unknown
                    | vesl_core::RejectionReason::RbacDenied { .. },
            } => GuardOutcome::Unknown,
            vesl_core::PokeOutcome::Crashed { .. } => GuardOutcome::Crashed,
            _ => GuardOutcome::Unknown,
        }
    }
}

/// Typed outcome for `kv-graft` pokes.
///
/// Decoded by [`PokeOutcome::as_kv_outcome`] (see [`KvOutcomeExt`]).
/// Use to pattern-match on the specific rejection variant the
/// kernel produced — `Error { msg }` for the generic cord-typed
/// kernel error, named struct variants for typed rejections,
/// `Denied { reason }` for gate-clean-deny.
#[derive(Debug)]
pub enum KvOutcome {
    /// Kernel accepted the poke. `effect_tags` are the head
    /// tags of every emitted effect — typically a single
    /// `*-accepted` or graft-specific success tag.
    Accepted { effect_tags: Vec<String> },
    /// `[%<graft>-error msg=@t]` — cord-typed kernel error.
    Error { msg: String },
    /// Kernel emitted no effects (collapses to
    /// `RejectionReason::Unknown`) or an RBAC pre-check denied
    /// the poke before it reached the kernel.
    Unknown,
    /// Driver-level failure (timeout, NockAppError, protocol
    /// violation). Mirrors `PokeOutcome::Crashed`.
    Crashed,
}

/// Extension trait — decodes a [`vesl_core::PokeOutcome`] into a
/// typed [`KvOutcome`] when the underlying effect came from
/// `kv-graft`. Other grafts' effects collapse to
/// [`KvOutcome::Unknown`].
pub trait KvOutcomeExt {
    fn as_kv_outcome(&self) -> KvOutcome;
}

impl KvOutcomeExt for vesl_core::PokeOutcome {
    fn as_kv_outcome(&self) -> KvOutcome {
        match self {
            vesl_core::PokeOutcome::Accepted { effects } => {
                KvOutcome::Accepted {
                    effect_tags: vesl_core::effect_head_tags(effects),
                }
            }
            vesl_core::PokeOutcome::Rejected {
                reason: vesl_core::RejectionReason::KernelError { cord, .. },
            } if cord.starts_with("kv-graft:") => {
                KvOutcome::Error { msg: cord.clone() }
            }
            vesl_core::PokeOutcome::Rejected {
                reason: vesl_core::RejectionReason::Unknown
                    | vesl_core::RejectionReason::RbacDenied { .. },
            } => KvOutcome::Unknown,
            vesl_core::PokeOutcome::Crashed { .. } => KvOutcome::Crashed,
            _ => KvOutcome::Unknown,
        }
    }
}

/// Typed outcome for `log-graft` pokes.
///
/// Decoded by [`PokeOutcome::as_log_outcome`] (see [`LogOutcomeExt`]).
/// Use to pattern-match on the specific rejection variant the
/// kernel produced — `Error { msg }` for the generic cord-typed
/// kernel error, named struct variants for typed rejections,
/// `Denied { reason }` for gate-clean-deny.
#[derive(Debug)]
pub enum LogOutcome {
    /// Kernel accepted the poke. `effect_tags` are the head
    /// tags of every emitted effect — typically a single
    /// `*-accepted` or graft-specific success tag.
    Accepted { effect_tags: Vec<String> },
    /// `[%<graft>-error msg=@t]` — cord-typed kernel error.
    Error { msg: String },
    /// Kernel emitted no effects (collapses to
    /// `RejectionReason::Unknown`) or an RBAC pre-check denied
    /// the poke before it reached the kernel.
    Unknown,
    /// Driver-level failure (timeout, NockAppError, protocol
    /// violation). Mirrors `PokeOutcome::Crashed`.
    Crashed,
}

/// Extension trait — decodes a [`vesl_core::PokeOutcome`] into a
/// typed [`LogOutcome`] when the underlying effect came from
/// `log-graft`. Other grafts' effects collapse to
/// [`LogOutcome::Unknown`].
pub trait LogOutcomeExt {
    fn as_log_outcome(&self) -> LogOutcome;
}

impl LogOutcomeExt for vesl_core::PokeOutcome {
    fn as_log_outcome(&self) -> LogOutcome {
        match self {
            vesl_core::PokeOutcome::Accepted { effects } => {
                LogOutcome::Accepted {
                    effect_tags: vesl_core::effect_head_tags(effects),
                }
            }
            vesl_core::PokeOutcome::Rejected {
                reason: vesl_core::RejectionReason::KernelError { cord, .. },
            } if cord.starts_with("log-graft:") => {
                LogOutcome::Error { msg: cord.clone() }
            }
            vesl_core::PokeOutcome::Rejected {
                reason: vesl_core::RejectionReason::Unknown
                    | vesl_core::RejectionReason::RbacDenied { .. },
            } => LogOutcome::Unknown,
            vesl_core::PokeOutcome::Crashed { .. } => LogOutcome::Crashed,
            _ => LogOutcome::Unknown,
        }
    }
}

/// Typed outcome for `mint-graft` pokes.
///
/// Decoded by [`PokeOutcome::as_mint_outcome`] (see [`MintOutcomeExt`]).
/// Use to pattern-match on the specific rejection variant the
/// kernel produced — `Error { msg }` for the generic cord-typed
/// kernel error, named struct variants for typed rejections,
/// `Denied { reason }` for gate-clean-deny.
#[derive(Debug)]
pub enum MintOutcome {
    /// Kernel accepted the poke. `effect_tags` are the head
    /// tags of every emitted effect — typically a single
    /// `*-accepted` or graft-specific success tag.
    Accepted { effect_tags: Vec<String> },
    /// `[%<graft>-error msg=@t]` — cord-typed kernel error.
    Error { msg: String },
    /// Kernel emitted no effects (collapses to
    /// `RejectionReason::Unknown`) or an RBAC pre-check denied
    /// the poke before it reached the kernel.
    Unknown,
    /// Driver-level failure (timeout, NockAppError, protocol
    /// violation). Mirrors `PokeOutcome::Crashed`.
    Crashed,
}

/// Extension trait — decodes a [`vesl_core::PokeOutcome`] into a
/// typed [`MintOutcome`] when the underlying effect came from
/// `mint-graft`. Other grafts' effects collapse to
/// [`MintOutcome::Unknown`].
pub trait MintOutcomeExt {
    fn as_mint_outcome(&self) -> MintOutcome;
}

impl MintOutcomeExt for vesl_core::PokeOutcome {
    fn as_mint_outcome(&self) -> MintOutcome {
        match self {
            vesl_core::PokeOutcome::Accepted { effects } => {
                MintOutcome::Accepted {
                    effect_tags: vesl_core::effect_head_tags(effects),
                }
            }
            vesl_core::PokeOutcome::Rejected {
                reason: vesl_core::RejectionReason::KernelError { cord, .. },
            } if cord.starts_with("mint-graft:") => {
                MintOutcome::Error { msg: cord.clone() }
            }
            vesl_core::PokeOutcome::Rejected {
                reason: vesl_core::RejectionReason::Unknown
                    | vesl_core::RejectionReason::RbacDenied { .. },
            } => MintOutcome::Unknown,
            vesl_core::PokeOutcome::Crashed { .. } => MintOutcome::Crashed,
            _ => MintOutcome::Unknown,
        }
    }
}

/// Typed outcome for `queue-graft` pokes.
///
/// Decoded by [`PokeOutcome::as_queue_outcome`] (see [`QueueOutcomeExt`]).
/// Use to pattern-match on the specific rejection variant the
/// kernel produced — `Error { msg }` for the generic cord-typed
/// kernel error, named struct variants for typed rejections,
/// `Denied { reason }` for gate-clean-deny.
#[derive(Debug)]
pub enum QueueOutcome {
    /// Kernel accepted the poke. `effect_tags` are the head
    /// tags of every emitted effect — typically a single
    /// `*-accepted` or graft-specific success tag.
    Accepted { effect_tags: Vec<String> },
    /// `[%<graft>-error msg=@t]` — cord-typed kernel error.
    Error { msg: String },
    /// Kernel emitted no effects (collapses to
    /// `RejectionReason::Unknown`) or an RBAC pre-check denied
    /// the poke before it reached the kernel.
    Unknown,
    /// Driver-level failure (timeout, NockAppError, protocol
    /// violation). Mirrors `PokeOutcome::Crashed`.
    Crashed,
}

/// Extension trait — decodes a [`vesl_core::PokeOutcome`] into a
/// typed [`QueueOutcome`] when the underlying effect came from
/// `queue-graft`. Other grafts' effects collapse to
/// [`QueueOutcome::Unknown`].
pub trait QueueOutcomeExt {
    fn as_queue_outcome(&self) -> QueueOutcome;
}

impl QueueOutcomeExt for vesl_core::PokeOutcome {
    fn as_queue_outcome(&self) -> QueueOutcome {
        match self {
            vesl_core::PokeOutcome::Accepted { effects } => {
                QueueOutcome::Accepted {
                    effect_tags: vesl_core::effect_head_tags(effects),
                }
            }
            vesl_core::PokeOutcome::Rejected {
                reason: vesl_core::RejectionReason::KernelError { cord, .. },
            } if cord.starts_with("queue-graft:") => {
                QueueOutcome::Error { msg: cord.clone() }
            }
            vesl_core::PokeOutcome::Rejected {
                reason: vesl_core::RejectionReason::Unknown
                    | vesl_core::RejectionReason::RbacDenied { .. },
            } => QueueOutcome::Unknown,
            vesl_core::PokeOutcome::Crashed { .. } => QueueOutcome::Crashed,
            _ => QueueOutcome::Unknown,
        }
    }
}

/// Typed outcome for `rbac-graft` pokes.
///
/// Decoded by [`PokeOutcome::as_rbac_outcome`] (see [`RbacOutcomeExt`]).
/// Use to pattern-match on the specific rejection variant the
/// kernel produced — `Error { msg }` for the generic cord-typed
/// kernel error, named struct variants for typed rejections,
/// `Denied { reason }` for gate-clean-deny.
#[derive(Debug)]
pub enum RbacOutcome {
    /// Kernel accepted the poke. `effect_tags` are the head
    /// tags of every emitted effect — typically a single
    /// `*-accepted` or graft-specific success tag.
    Accepted { effect_tags: Vec<String> },
    /// `[%<graft>-error msg=@t]` — cord-typed kernel error.
    Error { msg: String },
    /// Kernel emitted no effects (collapses to
    /// `RejectionReason::Unknown`) or an RBAC pre-check denied
    /// the poke before it reached the kernel.
    Unknown,
    /// Driver-level failure (timeout, NockAppError, protocol
    /// violation). Mirrors `PokeOutcome::Crashed`.
    Crashed,
}

/// Extension trait — decodes a [`vesl_core::PokeOutcome`] into a
/// typed [`RbacOutcome`] when the underlying effect came from
/// `rbac-graft`. Other grafts' effects collapse to
/// [`RbacOutcome::Unknown`].
pub trait RbacOutcomeExt {
    fn as_rbac_outcome(&self) -> RbacOutcome;
}

impl RbacOutcomeExt for vesl_core::PokeOutcome {
    fn as_rbac_outcome(&self) -> RbacOutcome {
        match self {
            vesl_core::PokeOutcome::Accepted { effects } => {
                RbacOutcome::Accepted {
                    effect_tags: vesl_core::effect_head_tags(effects),
                }
            }
            vesl_core::PokeOutcome::Rejected {
                reason: vesl_core::RejectionReason::KernelError { cord, .. },
            } if cord.starts_with("rbac-graft:") => {
                RbacOutcome::Error { msg: cord.clone() }
            }
            vesl_core::PokeOutcome::Rejected {
                reason: vesl_core::RejectionReason::Unknown
                    | vesl_core::RejectionReason::RbacDenied { .. },
            } => RbacOutcome::Unknown,
            vesl_core::PokeOutcome::Crashed { .. } => RbacOutcome::Crashed,
            _ => RbacOutcome::Unknown,
        }
    }
}

/// Typed outcome for `registry-graft` pokes.
///
/// Decoded by [`PokeOutcome::as_registry_outcome`] (see [`RegistryOutcomeExt`]).
/// Use to pattern-match on the specific rejection variant the
/// kernel produced — `Error { msg }` for the generic cord-typed
/// kernel error, named struct variants for typed rejections,
/// `Denied { reason }` for gate-clean-deny.
#[derive(Debug)]
pub enum RegistryOutcome {
    /// Kernel accepted the poke. `effect_tags` are the head
    /// tags of every emitted effect — typically a single
    /// `*-accepted` or graft-specific success tag.
    Accepted { effect_tags: Vec<String> },
    /// `[%<graft>-error msg=@t]` — cord-typed kernel error.
    Error { msg: String },
    /// Kernel emitted no effects (collapses to
    /// `RejectionReason::Unknown`) or an RBAC pre-check denied
    /// the poke before it reached the kernel.
    Unknown,
    /// Driver-level failure (timeout, NockAppError, protocol
    /// violation). Mirrors `PokeOutcome::Crashed`.
    Crashed,
}

/// Extension trait — decodes a [`vesl_core::PokeOutcome`] into a
/// typed [`RegistryOutcome`] when the underlying effect came from
/// `registry-graft`. Other grafts' effects collapse to
/// [`RegistryOutcome::Unknown`].
pub trait RegistryOutcomeExt {
    fn as_registry_outcome(&self) -> RegistryOutcome;
}

impl RegistryOutcomeExt for vesl_core::PokeOutcome {
    fn as_registry_outcome(&self) -> RegistryOutcome {
        match self {
            vesl_core::PokeOutcome::Accepted { effects } => {
                RegistryOutcome::Accepted {
                    effect_tags: vesl_core::effect_head_tags(effects),
                }
            }
            vesl_core::PokeOutcome::Rejected {
                reason: vesl_core::RejectionReason::KernelError { cord, .. },
            } if cord.starts_with("registry-graft:") => {
                RegistryOutcome::Error { msg: cord.clone() }
            }
            vesl_core::PokeOutcome::Rejected {
                reason: vesl_core::RejectionReason::Unknown
                    | vesl_core::RejectionReason::RbacDenied { .. },
            } => RegistryOutcome::Unknown,
            vesl_core::PokeOutcome::Crashed { .. } => RegistryOutcome::Crashed,
            _ => RegistryOutcome::Unknown,
        }
    }
}

/// Typed outcome for `settle-graft` pokes.
///
/// Decoded by [`PokeOutcome::as_settle_outcome`] (see [`SettleOutcomeExt`]).
/// Use to pattern-match on the specific rejection variant the
/// kernel produced — `Error { msg }` for the generic cord-typed
/// kernel error, named struct variants for typed rejections,
/// `Denied { reason }` for gate-clean-deny.
#[derive(Debug)]
pub enum SettleOutcome {
    /// Kernel accepted the poke. `effect_tags` are the head
    /// tags of every emitted effect — typically a single
    /// `*-accepted` or graft-specific success tag.
    Accepted { effect_tags: Vec<String> },
    /// `[%<graft>-error msg=@t]` — cord-typed kernel error.
    Error { msg: String },
    /// `[%settle-register-rejected ...]` — typed rejection.
    RegisterRejected {
        hull: u64,
        existing_root: Vec<u8>,
    },
    /// `[%<graft>-denied reason=@t]` — gate-clean-deny.
    Denied { reason: String },
    /// Kernel emitted no effects (collapses to
    /// `RejectionReason::Unknown`) or an RBAC pre-check denied
    /// the poke before it reached the kernel.
    Unknown,
    /// Driver-level failure (timeout, NockAppError, protocol
    /// violation). Mirrors `PokeOutcome::Crashed`.
    Crashed,
}

/// Extension trait — decodes a [`vesl_core::PokeOutcome`] into a
/// typed [`SettleOutcome`] when the underlying effect came from
/// `settle-graft`. Other grafts' effects collapse to
/// [`SettleOutcome::Unknown`].
pub trait SettleOutcomeExt {
    fn as_settle_outcome(&self) -> SettleOutcome;
}

impl SettleOutcomeExt for vesl_core::PokeOutcome {
    fn as_settle_outcome(&self) -> SettleOutcome {
        match self {
            vesl_core::PokeOutcome::Accepted { effects } => {
                SettleOutcome::Accepted {
                    effect_tags: vesl_core::effect_head_tags(effects),
                }
            }
            vesl_core::PokeOutcome::Rejected {
                reason: vesl_core::RejectionReason::KernelError { cord, .. },
            } if cord.starts_with("settle-graft:") => {
                SettleOutcome::Error { msg: cord.clone() }
            }
            vesl_core::PokeOutcome::Rejected {
                reason: vesl_core::RejectionReason::KernelRejected { tag, raw_effects },
            } if tag == "settle-register-rejected" => {
                let _ = raw_effects;
                SettleOutcome::RegisterRejected {
                    hull: 0,
                    existing_root: Vec::new(),
                }
            }
            vesl_core::PokeOutcome::Rejected {
                reason: vesl_core::RejectionReason::GateDenied { reason, .. },
            } if reason.starts_with("settle-graft:") => {
                SettleOutcome::Denied { reason: reason.clone() }
            }
            vesl_core::PokeOutcome::Rejected {
                reason: vesl_core::RejectionReason::Unknown
                    | vesl_core::RejectionReason::RbacDenied { .. },
            } => SettleOutcome::Unknown,
            vesl_core::PokeOutcome::Crashed { .. } => SettleOutcome::Crashed,
            _ => SettleOutcome::Unknown,
        }
    }
}

/// Typed outcome for `validate-graft` pokes.
///
/// Decoded by [`PokeOutcome::as_validate_outcome`] (see [`ValidateOutcomeExt`]).
/// Use to pattern-match on the specific rejection variant the
/// kernel produced — `Error { msg }` for the generic cord-typed
/// kernel error, named struct variants for typed rejections,
/// `Denied { reason }` for gate-clean-deny.
#[derive(Debug)]
pub enum ValidateOutcome {
    /// Kernel accepted the poke. `effect_tags` are the head
    /// tags of every emitted effect — typically a single
    /// `*-accepted` or graft-specific success tag.
    Accepted { effect_tags: Vec<String> },
    /// `[%<graft>-error msg=@t]` — cord-typed kernel error.
    Error { msg: String },
    /// `[%validate-rejected ...]` — typed rejection.
    Rejected {
        cause_tag: String,
        reason: String,
    },
    /// Kernel emitted no effects (collapses to
    /// `RejectionReason::Unknown`) or an RBAC pre-check denied
    /// the poke before it reached the kernel.
    Unknown,
    /// Driver-level failure (timeout, NockAppError, protocol
    /// violation). Mirrors `PokeOutcome::Crashed`.
    Crashed,
}

/// Extension trait — decodes a [`vesl_core::PokeOutcome`] into a
/// typed [`ValidateOutcome`] when the underlying effect came from
/// `validate-graft`. Other grafts' effects collapse to
/// [`ValidateOutcome::Unknown`].
pub trait ValidateOutcomeExt {
    fn as_validate_outcome(&self) -> ValidateOutcome;
}

impl ValidateOutcomeExt for vesl_core::PokeOutcome {
    fn as_validate_outcome(&self) -> ValidateOutcome {
        match self {
            vesl_core::PokeOutcome::Accepted { effects } => {
                ValidateOutcome::Accepted {
                    effect_tags: vesl_core::effect_head_tags(effects),
                }
            }
            vesl_core::PokeOutcome::Rejected {
                reason: vesl_core::RejectionReason::KernelError { cord, .. },
            } if cord.starts_with("validate-graft:") => {
                ValidateOutcome::Error { msg: cord.clone() }
            }
            vesl_core::PokeOutcome::Rejected {
                reason: vesl_core::RejectionReason::KernelRejected { tag, raw_effects },
            } if tag == "validate-rejected" => {
                let _ = raw_effects;
                ValidateOutcome::Rejected {
                    cause_tag: String::new(),
                    reason: String::new(),
                }
            }
            vesl_core::PokeOutcome::Rejected {
                reason: vesl_core::RejectionReason::Unknown
                    | vesl_core::RejectionReason::RbacDenied { .. },
            } => ValidateOutcome::Unknown,
            vesl_core::PokeOutcome::Crashed { .. } => ValidateOutcome::Crashed,
            _ => ValidateOutcome::Unknown,
        }
    }
}

impl crate::GraftTestHarness {
    // -- batch-graft -----------------------------------------------------

    /// Send `[%batch-init ...]`. Delegates to `vesl_core::build_batch_init_poke`.
    pub async fn batch_init(&mut self, threshold: u64) -> anyhow::Result<vesl_core::PokeOutcome> {
        let slab = vesl_core::build_batch_init_poke(threshold);
        self.poke_slab(slab).await
    }

    /// Send `[%batch-add ...]`. Delegates to `vesl_core::build_batch_add_poke`.
    pub async fn batch_add(&mut self, intent_jammed: &[u8]) -> anyhow::Result<vesl_core::PokeOutcome> {
        let slab = vesl_core::build_batch_add_poke(intent_jammed);
        self.poke_slab(slab).await
    }

    /// Send `[%batch-add ...]`. Delegates to `vesl_core::build_batch_add_poke_from_noun`.
    pub async fn batch_add_from_noun(&mut self, payload: &NounSlab) -> anyhow::Result<vesl_core::PokeOutcome> {
        let slab = vesl_core::build_batch_add_poke_from_noun(payload);
        self.poke_slab(slab).await
    }

    /// Send `[%batch-flush ...]`. Delegates to `vesl_core::build_batch_flush_poke`.
    pub async fn batch_flush(&mut self) -> anyhow::Result<vesl_core::PokeOutcome> {
        let slab = vesl_core::build_batch_flush_poke();
        self.poke_slab(slab).await
    }


    // -- clock-graft -----------------------------------------------------

    /// Send `[%clock-tick ...]`. Delegates to `vesl_core::build_clock_tick_poke`.
    pub async fn clock_tick(&mut self) -> anyhow::Result<vesl_core::PokeOutcome> {
        let slab = vesl_core::build_clock_tick_poke();
        self.poke_slab(slab).await
    }


    // -- counter-graft -----------------------------------------------------

    /// Send `[%counter-increment ...]`. Delegates to `vesl_core::build_counter_increment_poke`.
    pub async fn counter_increment(&mut self, name: &str) -> anyhow::Result<vesl_core::PokeOutcome> {
        let slab = vesl_core::build_counter_increment_poke(name);
        self.poke_slab(slab).await
    }

    /// Send `[%counter-reset ...]`. Delegates to `vesl_core::build_counter_reset_poke`.
    pub async fn counter_reset(&mut self, name: &str) -> anyhow::Result<vesl_core::PokeOutcome> {
        let slab = vesl_core::build_counter_reset_poke(name);
        self.poke_slab(slab).await
    }

    /// Send `[%counter-set ...]`. Delegates to `vesl_core::build_counter_set_poke`.
    pub async fn counter_set(&mut self, name: &str, value: u64) -> anyhow::Result<vesl_core::PokeOutcome> {
        let slab = vesl_core::build_counter_set_poke(name, value);
        self.poke_slab(slab).await
    }


    // -- forge-graft -----------------------------------------------------

    /// Send `[%forge-prove ...]`. Delegates to `vesl_core::build_forge_prove_poke`.
    pub async fn forge_prove(&mut self, hull: u64, note_id: u64, data: &[u8]) -> anyhow::Result<vesl_core::PokeOutcome> {
        let slab = vesl_core::build_forge_prove_poke(hull, note_id, data);
        self.poke_slab(slab).await
    }


    // -- guard-graft -----------------------------------------------------

    /// Send `[%guard-register ...]`. Delegates to `vesl_core::build_guard_register_poke`.
    pub async fn guard_register(&mut self, hull: u64, root: &Tip5Hash) -> anyhow::Result<vesl_core::PokeOutcome> {
        let slab = vesl_core::build_guard_register_poke(hull, root);
        self.poke_slab(slab).await
    }

    /// Send `[%guard-check ...]`. Delegates to `vesl_core::build_guard_check_poke`.
    pub async fn guard_check(&mut self, hull: u64, data: &[u8]) -> anyhow::Result<vesl_core::PokeOutcome> {
        let slab = vesl_core::build_guard_check_poke(hull, data);
        self.poke_slab(slab).await
    }


    // -- kv-graft -----------------------------------------------------

    /// Send `[%kv-set ...]`. Delegates to `vesl_core::build_kv_set_poke`.
    pub async fn kv_set(&mut self, key: &str, value: &[u8]) -> anyhow::Result<vesl_core::PokeOutcome> {
        let slab = vesl_core::build_kv_set_poke(key, value);
        self.poke_slab(slab).await
    }

    /// Send `[%kv-delete ...]`. Delegates to `vesl_core::build_kv_delete_poke`.
    pub async fn kv_delete(&mut self, key: &str) -> anyhow::Result<vesl_core::PokeOutcome> {
        let slab = vesl_core::build_kv_delete_poke(key);
        self.poke_slab(slab).await
    }


    // -- log-graft -----------------------------------------------------

    /// Send `[%log-append ...]`. Delegates to `vesl_core::build_log_append_poke`.
    pub async fn log_append(&mut self, tag: &str, data_jammed: &[u8]) -> anyhow::Result<vesl_core::PokeOutcome> {
        let slab = vesl_core::build_log_append_poke(tag, data_jammed);
        self.poke_slab(slab).await
    }

    /// Send `[%log-append ...]`. Delegates to `vesl_core::build_log_append_poke_from_noun`.
    pub async fn log_append_from_noun(&mut self, tag: &str, payload: &NounSlab) -> anyhow::Result<vesl_core::PokeOutcome> {
        let slab = vesl_core::build_log_append_poke_from_noun(tag, payload);
        self.poke_slab(slab).await
    }


    // -- mint-graft -----------------------------------------------------

    /// Send `[%mint-commit ...]`. Delegates to `vesl_core::build_mint_commit_poke`.
    pub async fn mint_commit(&mut self, hull: u64, root: &Tip5Hash) -> anyhow::Result<vesl_core::PokeOutcome> {
        let slab = vesl_core::build_mint_commit_poke(hull, root);
        self.poke_slab(slab).await
    }


    // -- queue-graft -----------------------------------------------------

    /// Send `[%queue-push ...]`. Delegates to `vesl_core::build_queue_push_poke`.
    pub async fn queue_push(&mut self, body_jammed: &[u8]) -> anyhow::Result<vesl_core::PokeOutcome> {
        let slab = vesl_core::build_queue_push_poke(body_jammed);
        self.poke_slab(slab).await
    }

    /// Send `[%queue-push ...]`. Delegates to `vesl_core::build_queue_push_poke_from_noun`.
    pub async fn queue_push_from_noun(&mut self, payload: &NounSlab) -> anyhow::Result<vesl_core::PokeOutcome> {
        let slab = vesl_core::build_queue_push_poke_from_noun(payload);
        self.poke_slab(slab).await
    }

    /// Send `[%queue-pop ...]`. Delegates to `vesl_core::build_queue_pop_poke`.
    pub async fn queue_pop(&mut self) -> anyhow::Result<vesl_core::PokeOutcome> {
        let slab = vesl_core::build_queue_pop_poke();
        self.poke_slab(slab).await
    }

    /// Send `[%queue-clear ...]`. Delegates to `vesl_core::build_queue_clear_poke`.
    pub async fn queue_clear(&mut self) -> anyhow::Result<vesl_core::PokeOutcome> {
        let slab = vesl_core::build_queue_clear_poke();
        self.poke_slab(slab).await
    }


    // -- rbac-graft -----------------------------------------------------

    /// Send `[%rbac-grant ...]`. Delegates to `vesl_core::build_rbac_grant_poke`.
    pub async fn rbac_grant(&mut self, pubkey: u64, perms: &[&str]) -> anyhow::Result<vesl_core::PokeOutcome> {
        let slab = vesl_core::build_rbac_grant_poke(pubkey, perms);
        self.poke_slab(slab).await
    }

    /// Send `[%rbac-revoke ...]`. Delegates to `vesl_core::build_rbac_revoke_poke`.
    pub async fn rbac_revoke(&mut self, pubkey: u64, perms: &[&str]) -> anyhow::Result<vesl_core::PokeOutcome> {
        let slab = vesl_core::build_rbac_revoke_poke(pubkey, perms);
        self.poke_slab(slab).await
    }


    // -- registry-graft -----------------------------------------------------

    /// Send `[%registry-put ...]`. Delegates to `vesl_core::build_registry_put_poke`.
    pub async fn registry_put(&mut self, key: u64, record_jammed: &[u8]) -> anyhow::Result<vesl_core::PokeOutcome> {
        let slab = vesl_core::build_registry_put_poke(key, record_jammed);
        self.poke_slab(slab).await
    }

    /// Send `[%registry-put ...]`. Delegates to `vesl_core::build_registry_put_poke_from_noun`.
    pub async fn registry_put_from_noun(&mut self, key: u64, record: &NounSlab) -> anyhow::Result<vesl_core::PokeOutcome> {
        let slab = vesl_core::build_registry_put_poke_from_noun(key, record);
        self.poke_slab(slab).await
    }

    /// Send `[%registry-update ...]`. Delegates to `vesl_core::build_registry_update_poke`.
    pub async fn registry_update(&mut self, key: u64, record_jammed: &[u8]) -> anyhow::Result<vesl_core::PokeOutcome> {
        let slab = vesl_core::build_registry_update_poke(key, record_jammed);
        self.poke_slab(slab).await
    }

    /// Send `[%registry-update ...]`. Delegates to `vesl_core::build_registry_update_poke_from_noun`.
    pub async fn registry_update_from_noun(&mut self, key: u64, record: &NounSlab) -> anyhow::Result<vesl_core::PokeOutcome> {
        let slab = vesl_core::build_registry_update_poke_from_noun(key, record);
        self.poke_slab(slab).await
    }

    /// Send `[%registry-del ...]`. Delegates to `vesl_core::build_registry_del_poke`.
    pub async fn registry_del(&mut self, key: u64) -> anyhow::Result<vesl_core::PokeOutcome> {
        let slab = vesl_core::build_registry_del_poke(key);
        self.poke_slab(slab).await
    }


    // -- settle-graft -----------------------------------------------------

    /// Send `[%settle-register ...]`. Delegates to `vesl_core::build_settle_register_poke`.
    pub async fn settle_register(&mut self, hull: u64, root: &Tip5Hash) -> anyhow::Result<vesl_core::PokeOutcome> {
        let slab = vesl_core::build_settle_register_poke(hull, root);
        self.poke_slab(slab).await
    }

    /// Send `[%settle-verify ...]`. Delegates to `vesl_core::build_settle_verify_poke`.
    pub async fn settle_verify(&mut self, note_id: u64, hull: u64, root: &Tip5Hash, data: &[u8]) -> anyhow::Result<vesl_core::PokeOutcome> {
        let slab = vesl_core::build_settle_verify_poke(note_id, hull, root, data);
        self.poke_slab(slab).await
    }

    /// Send `[%settle-note ...]`. Delegates to `vesl_core::build_settle_note_poke`.
    pub async fn settle_note(&mut self, note_id: u64, hull: u64, root: &Tip5Hash, data: &[u8]) -> anyhow::Result<vesl_core::PokeOutcome> {
        let slab = vesl_core::build_settle_note_poke(note_id, hull, root, data);
        self.poke_slab(slab).await
    }


    // -- validate-graft -----------------------------------------------------

    /// Send `[%validate-init ...]`. Delegates to `vesl_core::build_validate_init_poke`.
    pub async fn validate_init(&mut self, cause_tag: &str, rules: &[ValidateRule]) -> anyhow::Result<vesl_core::PokeOutcome> {
        let slab = vesl_core::build_validate_init_poke(cause_tag, rules);
        self.poke_slab(slab).await
    }

    /// Send `[%validate-clear ...]`. Delegates to `vesl_core::build_validate_clear_poke`.
    pub async fn validate_clear(&mut self, cause_tag: &str) -> anyhow::Result<vesl_core::PokeOutcome> {
        let slab = vesl_core::build_validate_clear_poke(cause_tag);
        self.poke_slab(slab).await
    }

}
