#!/usr/bin/env bash
# Validate every upstream PIN in vesl-nockup.
#
# vesl-nockup is the canonical-pin source-of-truth for the ecosystem.
# Three pin streams, each duplicated across two sites that MUST agree:
#
#   NOCK_PIN
#     sync.sh                                ×1 site (canonical default)
#     .github/workflows/ci.yml               ×1 site (CI env)
#     templates/*/Cargo.toml                 ×3 git-deps per template
#                                             (rewritten by sync.sh from
#                                              path-deps; should all match
#                                              the canonical)
#
#   VESL_CORE_PIN
#     sync.sh                                ×1 site
#     .github/workflows/ci.yml               ×1 site
#
#   VESL_WALLET_PIN
#     sync.sh                                ×1 site
#     .github/workflows/ci.yml               ×1 site
#
# Plus .sync-pins.toml (auto-generated by sync.sh; should match the
# canonicals; drift means the last sync ran with different pins than
# the current canonicals).
#
# Checks performed:
#   1. Shape: every full-SHA value is 40-char lowercase hex.
#   2. Agreement: sync.sh canonical == ci.yml env for each pin.
#   3. Bundle sync: .sync-pins.toml records match canonical (warn).
#   4. Templates: every templates/*/Cargo.toml nockchain git-dep
#      uses the canonical NOCK_PIN. M-23 (templates/vesl drift) surfaces
#      here as a warning.
#   5. Existence: all three SHAs reachable upstream (sibling rev-parse
#      → ls-remote fallback).
#
# Exit 0 on clean (warnings allowed). Exit 1 on agreement / shape failure.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

status=0
warnings=0

err()  { echo "FAIL: $*" >&2; status=1; }
warn() { echo "warn: $*" >&2; warnings=$((warnings + 1)); }
ok()   { echo "ok   $*"; }

# Extract canonical default from sync.sh: NAME="${NAME:-<sha>}"
extract_sync_canonical() {
    local key="$1"
    grep -oE "${key}=\"\\\$\\{${key}:-[0-9a-f]{40}" sync.sh \
        | grep -oE '[0-9a-f]{40}$' || true
}

# Extract NAME: <sha> from a YAML env block.
extract_yaml_pin() {
    local file="$1" key="$2"
    grep -E "^[[:space:]]+$key:[[:space:]]*[0-9a-f]+" "$file" 2>/dev/null \
        | grep -oE '[0-9a-f]{40}' | head -1 || true
}

# Extract `pin = "<sha>"` for a section in .sync-pins.toml.
extract_pins_toml() {
    local section="$1" file=".sync-pins.toml"
    [[ -f "$file" ]] || { echo ""; return; }
    awk -v sec="[$section]" '
        $0 == sec { in_sec=1; next }
        /^\[/      { in_sec=0 }
        in_sec && /^pin/ {
            gsub(/[^0-9a-f]/, "")
            print
            exit
        }
    ' "$file"
}

validate_shape() {
    local label="$1" sha="$2"
    if [[ -z "$sha" ]]; then
        err "$label: no SHA found"; return 1
    fi
    if [[ ! "$sha" =~ ^[0-9a-f]{40}$ ]]; then
        err "$label: '$sha' is not 40-char lowercase hex"; return 1
    fi
    return 0
}

validate_existence() {
    local repo_path="$1" repo_url="$2" sha="$3" label="$4"
    if [[ -d "$repo_path/.git" ]] && \
       git -C "$repo_path" cat-file -t "$sha" >/dev/null 2>&1; then
        return 0
    fi
    if git ls-remote --exit-code "$repo_url" "$sha" >/dev/null 2>&1; then
        return 0
    fi
    warn "$label: $sha not in sibling $repo_path and not reachable at $repo_url"
}

# Pin definitions: key | sibling path | repo url
pins=(
    "NOCK_PIN|../nockchain|https://github.com/nockchain/nockchain"
    "VESL_CORE_PIN|../vesl-core|https://github.com/zkvesl/vesl-core"
    "VESL_WALLET_PIN|../vesl-wallet|https://github.com/zkvesl/vesl-wallet"
)

declare -A canonical

for entry in "${pins[@]}"; do
    IFS='|' read -r key repo_path repo_url <<< "$entry"

    sync_sha=$(extract_sync_canonical "$key")
    ci_sha=$(extract_yaml_pin .github/workflows/ci.yml "$key")

    validate_shape "$key sync.sh" "$sync_sha" || continue
    validate_shape "$key ci.yml" "$ci_sha"   || continue

    if [[ "$sync_sha" != "$ci_sha" ]]; then
        err "$key: sync.sh ($sync_sha) != ci.yml ($ci_sha)"
        continue
    fi

    canonical[$key]="$sync_sha"
    ok "$key: sync.sh + ci.yml agree ($sync_sha)"

    validate_existence "$repo_path" "$repo_url" "$sync_sha" "$key"
done

# --- .sync-pins.toml sanity ---
if [[ -f .sync-pins.toml ]]; then
    for entry in "vesl-core:VESL_CORE_PIN" "vesl-wallet:VESL_WALLET_PIN" "nockchain:NOCK_PIN"; do
        section="${entry%%:*}"
        key="${entry##*:}"
        recorded=$(extract_pins_toml "$section")
        canon="${canonical[$key]:-}"
        if [[ -n "$canon" && -n "$recorded" && "$recorded" != "$canon" ]]; then
            warn ".sync-pins.toml [$section] pin=$recorded != canonical $key=$canon"
            warn "  re-run ./sync.sh to refresh the bundle (and the recorded pin)"
        fi
    done
fi

# --- Templates: NOCK_PIN drift (audit M-23) ---
nock_canon="${canonical[NOCK_PIN]:-}"
if [[ -n "$nock_canon" ]]; then
    drift_templates=""
    for tpl in templates/*/Cargo.toml; do
        [[ -f "$tpl" ]] || continue
        mapfile -t tpl_revs < <(grep -E "git[[:space:]]*=[[:space:]]*\"[^\"]*nockchain/nockchain" "$tpl" 2>/dev/null \
            | grep -oE 'rev[[:space:]]*=[[:space:]]*"[0-9a-f]{40}"' \
            | grep -oE '[0-9a-f]{40}')
        for sha in "${tpl_revs[@]}"; do
            if [[ "$sha" != "$nock_canon" ]]; then
                drift_templates+="$tpl ($sha)\n"
                break
            fi
        done
    done
    if [[ -n "$drift_templates" ]]; then
        warn "NOCK_PIN drift in templates (canonical: $nock_canon):"
        printf "%b" "$drift_templates" | sed 's/^/  /' >&2
        warn "  bump with: scripts/bump-pin.sh nock $nock_canon"
    fi
fi

# --- Summary ---
echo ""
if [[ $status -eq 0 ]]; then
    if [[ $warnings -gt 0 ]]; then
        echo "ok with $warnings warning(s) — see above"
    else
        echo "ok — all pins valid and agree"
    fi
else
    echo "FAIL — pin agreement broken ($warnings warning(s))" >&2
fi

exit $status
