//! `graft-inject codegen harness-methods` — read
//! `hoon/lib/harness-bindings.toml`, cross-check every binding against
//! the corresponding `*-graft.toml` poke arm, and emit
//! `test/vesl-test/src/generated_harness.rs`.

use std::fs;
use std::path::Path;

use anyhow::{Context, Result, bail};

use crate::harness_bindings::{
    HarnessGraftBindings, HarnessPoke, LoadedHarnessBindings, load_harness_bindings,
    validate_bindings_against_grafts,
};
use crate::manifest::discover_grafts;

/// `graft-inject codegen harness-methods` entry point. Loads the
/// sidecar, cross-checks every `(graft, tag)` against the matching
/// `*-graft.toml` poke body, and emits Rust source for
/// `test/vesl-test/src/generated_harness.rs`.
///
/// The generated file contains, in order:
///
/// 1. A provenance header (sidecar path + sha256).
/// 2. `use` lines for the non-primitive types referenced by any bound
///    arg (`Tip5Hash`, `NounSlab`, `ValidateRule`, `ProofNode`).
/// 3. One `pub enum <Graft>Outcome { ... }` per graft with bound
///    pokes, carrying typed variants for the graft's error / rejected /
///    denied effects.
/// 4. One `pub trait <Graft>OutcomeExt` per graft with an
///    `as_<graft>_outcome(&self) -> <Graft>Outcome` method, plus an
///    `impl <Graft>OutcomeExt for vesl_core::PokeOutcome`.
/// 5. A single `impl crate::GraftTestHarness { ... }` block with one
///    async method per bound poke arm, delegating to
///    `vesl_core::<builder>(...)` and returning
///    `anyhow::Result<vesl_core::PokeOutcome>`.
pub(crate) fn run_codegen_harness_methods(
    bindings_path: &Path,
    lib_dir: &Path,
    out: Option<&Path>,
) -> Result<()> {
    let loaded = load_harness_bindings(bindings_path)?;
    let grafts = if lib_dir.is_dir() {
        discover_grafts(lib_dir)
            .with_context(|| format!("discovering grafts under {}", lib_dir.display()))?
    } else {
        bail!(
            "lib dir {} is not a directory; harness-methods codegen reads \
             every graft manifest to cross-check bindings against poke arms",
            lib_dir.display()
        );
    };
    validate_bindings_against_grafts(&loaded.bindings, &grafts)?;
    let src = emit_harness_methods_rs(bindings_path, &loaded);
    match out {
        Some(p) => fs::write(p, &src)
            .with_context(|| format!("writing {}", p.display()))?,
        None => print!("{src}"),
    }
    Ok(())
}

/// Render the full generated `generated_harness.rs`.
pub(crate) fn emit_harness_methods_rs(
    source_path: &Path,
    loaded: &LoadedHarnessBindings,
) -> String {
    let mut s = String::new();
    s.push_str(
        "//! AUTO-GENERATED by `nockup-graft codegen harness-methods`.\n",
    );
    s.push_str(&format!(
        "//! Source: {} sha256:{}\n",
        source_path.display(),
        loaded.sha256
    ));
    s.push_str("//! Re-run after every harness-bindings change. Do not edit by hand.\n");
    s.push_str("//!\n");
    s.push_str("//! See `tools/graft-inject/src/harness_bindings.rs` for the sidecar\n");
    s.push_str("//! schema and `tools/graft-inject/src/codegen.rs` for the emitter.\n");
    s.push('\n');
    s.push_str("#![allow(unused_imports)]\n\n");

    let used = collect_used_types(loaded);
    if !used.is_empty() {
        for ident in &used {
            s.push_str(&render_use_line(ident));
        }
        s.push('\n');
    }

    // 3. + 4. — per-graft typed outcome enums + extension traits.
    for graft in &loaded.bindings.grafts {
        if !graft_has_typed_outcome(graft) {
            continue;
        }
        emit_outcome_enum(&mut s, graft);
        emit_outcome_ext_trait(&mut s, graft);
    }

    // 5. — single impl block holding every generated poke method.
    s.push_str("impl crate::GraftTestHarness {\n");
    let mut first = true;
    for graft in &loaded.bindings.grafts {
        if graft.pokes.is_empty() {
            continue;
        }
        if !first {
            s.push('\n');
        }
        first = false;
        s.push_str(&format!(
            "    // -- {}-graft -----------------------------------------------------\n\n",
            graft.name
        ));
        for poke in &graft.pokes {
            emit_poke_method(&mut s, poke);
        }
    }
    s.push_str("}\n");

    s
}

/// One generated method on `GraftTestHarness` per `[[graft.pokes]]`
/// entry. The body delegates to the existing `vesl_core::<builder>`
/// function and routes its `NounSlab` through `poke_slab`, which
/// returns the typed `PokeOutcome`.
fn emit_poke_method(s: &mut String, poke: &HarnessPoke) {
    s.push_str(&format!(
        "    /// Send `[%{tag} ...]`. Delegates to `vesl_core::{builder}`.\n",
        tag = poke.tag,
        builder = poke.builder,
    ));

    let mut params = String::new();
    let mut forwards = String::new();
    for (i, arg) in poke.args.iter().enumerate() {
        if i > 0 {
            params.push_str(", ");
            forwards.push_str(", ");
        }
        params.push_str(&format!("{}: {}", arg.name, arg.rust));
        forwards.push_str(&arg.name);
    }
    let sep = if poke.args.is_empty() { "" } else { ", " };
    s.push_str(&format!(
        "    pub async fn {method}(&mut self{sep}{params}) \
         -> anyhow::Result<vesl_core::PokeOutcome> {{\n",
        method = poke.method,
    ));
    s.push_str(&format!(
        "        let slab = vesl_core::{builder}({forwards});\n",
        builder = poke.builder,
    ));
    s.push_str("        self.poke_slab(slab).await\n");
    s.push_str("    }\n\n");
}

/// `pub enum <Graft>Outcome { Accepted, Error{msg}, <RejectedVariants>,
/// Denied{reason}, Unknown, Crashed }` — typed surface over the generic
/// `PokeOutcome`. Generated when the graft declares any error /
/// rejected / denied tag in the sidecar.
fn emit_outcome_enum(s: &mut String, graft: &HarnessGraftBindings) {
    let pascal = pascal_case(&graft.name);
    s.push_str(&format!("/// Typed outcome for `{}-graft` pokes.\n", graft.name));
    s.push_str("///\n");
    s.push_str("/// Decoded by [`PokeOutcome::");
    s.push_str(&format!("as_{}_outcome`]", graft.name));
    s.push_str(&format!(" (see [`{pascal}OutcomeExt`]).\n"));
    s.push_str("/// Use to pattern-match on the specific rejection variant the\n");
    s.push_str("/// kernel produced — `Error { msg }` for the generic cord-typed\n");
    s.push_str("/// kernel error, named struct variants for typed rejections,\n");
    s.push_str("/// `Denied { reason }` for gate-clean-deny.\n");
    s.push_str("#[derive(Debug)]\n");
    s.push_str(&format!("pub enum {pascal}Outcome {{\n"));
    s.push_str("    /// Kernel accepted the poke. `effect_tags` are the head\n");
    s.push_str("    /// tags of every emitted effect — typically a single\n");
    s.push_str("    /// `*-accepted` or graft-specific success tag.\n");
    s.push_str("    Accepted { effect_tags: Vec<String> },\n");

    // [%<graft>-error msg=@t]
    if !graft.errors.is_empty() {
        s.push_str("    /// `[%<graft>-error msg=@t]` — cord-typed kernel error.\n");
        s.push_str("    Error { msg: String },\n");
    }

    // [%<graft>-..-rejected ...]
    for rej in &graft.rejected {
        let variant = pascal_case(strip_graft_prefix(&rej.tag, &graft.name));
        s.push_str(&format!("    /// `[%{tag} ...]` — typed rejection.\n", tag = rej.tag));
        if rej.fields.is_empty() {
            s.push_str(&format!("    {variant},\n"));
        } else {
            s.push_str(&format!("    {variant} {{\n"));
            for f in &rej.fields {
                s.push_str(&format!("        {}: {},\n", f.name, f.rust));
            }
            s.push_str("    },\n");
        }
    }

    // [%<graft>-denied reason=@t]
    if !graft.denied.is_empty() {
        s.push_str("    /// `[%<graft>-denied reason=@t]` — gate-clean-deny.\n");
        s.push_str("    Denied { reason: String },\n");
    }

    s.push_str("    /// Kernel emitted no effects (collapses to\n");
    s.push_str("    /// `RejectionReason::Unknown`) or an RBAC pre-check denied\n");
    s.push_str("    /// the poke before it reached the kernel.\n");
    s.push_str("    Unknown,\n");
    s.push_str("    /// Driver-level failure (timeout, NockAppError, protocol\n");
    s.push_str("    /// violation). Mirrors `PokeOutcome::Crashed`.\n");
    s.push_str("    Crashed,\n");
    s.push_str("}\n\n");
}

/// `pub trait <Graft>OutcomeExt { fn as_<graft>_outcome(&self) ->
/// <Graft>Outcome; }` plus its `impl for vesl_core::PokeOutcome`. The
/// decoder walks the existing `PokeOutcome` shape and routes by
/// suffix-rules already enshrined in `classify_effects`:
///
/// - `Accepted { effects }` → `<Graft>Outcome::Accepted { effect_tags }`
/// - `Rejected { reason: KernelError { cord, .. } }` → `Error { msg }`
///   (only when the cord starts with `<graft>-graft:` so we don't pick
///   up another graft's error)
/// - `Rejected { reason: KernelRejected { tag, raw_effects } }` →
///   the named typed-rejection variant when the tag matches one of the
///   graft's declared `[[graft.rejected]]` entries
/// - `Rejected { reason: GateDenied { reason, .. } }` → `Denied { reason }`
///   (only when the tag matches the graft's `[[graft.denied]]`)
/// - everything else → `Unknown` / `Crashed`
fn emit_outcome_ext_trait(s: &mut String, graft: &HarnessGraftBindings) {
    let pascal = pascal_case(&graft.name);
    let trait_name = format!("{pascal}OutcomeExt");
    let method = format!("as_{}_outcome", graft.name);
    let outcome = format!("{pascal}Outcome");

    s.push_str("/// Extension trait — decodes a [`vesl_core::PokeOutcome`] into a\n");
    s.push_str(&format!("/// typed [`{outcome}`] when the underlying effect came from\n"));
    s.push_str(&format!("/// `{}-graft`. Other grafts' effects collapse to\n", graft.name));
    s.push_str(&format!("/// [`{outcome}::Unknown`].\n"));
    s.push_str(&format!("pub trait {trait_name} {{\n"));
    s.push_str(&format!("    fn {method}(&self) -> {outcome};\n"));
    s.push_str("}\n\n");

    s.push_str(&format!("impl {trait_name} for vesl_core::PokeOutcome {{\n"));
    s.push_str(&format!("    fn {method}(&self) -> {outcome} {{\n"));
    s.push_str("        match self {\n");
    s.push_str("            vesl_core::PokeOutcome::Accepted { effects } => {\n");
    s.push_str(&format!(
        "                {outcome}::Accepted {{\n",
    ));
    s.push_str("                    effect_tags: vesl_core::effect_head_tags(effects),\n");
    s.push_str("                }\n");
    s.push_str("            }\n");

    // KernelError { cord, raw_effects } — only when cord starts with `<graft>-graft:`
    if !graft.errors.is_empty() {
        let prefix = format!("{}-graft:", graft.name);
        s.push_str("            vesl_core::PokeOutcome::Rejected {\n");
        s.push_str("                reason: vesl_core::RejectionReason::KernelError { cord, .. },\n");
        s.push_str(&format!(
            "            }} if cord.starts_with({prefix:?}) => {{\n"
        ));
        s.push_str(&format!("                {outcome}::Error {{ msg: cord.clone() }}\n"));
        s.push_str("            }\n");
    }

    // KernelRejected { tag, raw_effects } — one match arm per declared rejection
    for rej in &graft.rejected {
        let variant = pascal_case(strip_graft_prefix(&rej.tag, &graft.name));
        s.push_str("            vesl_core::PokeOutcome::Rejected {\n");
        s.push_str("                reason: vesl_core::RejectionReason::KernelRejected { tag, raw_effects },\n");
        s.push_str(&format!(
            "            }} if tag == {tag:?} => {{\n",
            tag = rej.tag,
        ));
        if rej.fields.is_empty() {
            s.push_str(&format!("                let _ = raw_effects; {outcome}::{variant}\n"));
        } else {
            // For typed-rejection field decoding, default to a heuristic
            // that consumers extend in v2.0 (the current cut surfaces
            // raw_effects so callers can decode by hand if they need the
            // typed fields). The variant is constructed with default
            // values for primitives and empty for owned types; consumers
            // pattern-match on the variant for routing and reach for
            // raw_effects when they need the bound fields.
            s.push_str("                let _ = raw_effects;\n");
            s.push_str(&format!("                {outcome}::{variant} {{\n"));
            for f in &rej.fields {
                s.push_str(&format!(
                    "                    {name}: {default},\n",
                    name = f.name,
                    default = default_value_for(&f.rust),
                ));
            }
            s.push_str("                }\n");
        }
        s.push_str("            }\n");
    }

    // GateDenied — only when graft declared a denied tag
    if !graft.denied.is_empty() {
        let prefix = format!("{}-graft:", graft.name);
        s.push_str("            vesl_core::PokeOutcome::Rejected {\n");
        s.push_str("                reason: vesl_core::RejectionReason::GateDenied { reason, .. },\n");
        s.push_str(&format!(
            "            }} if reason.starts_with({prefix:?}) => {{\n"
        ));
        s.push_str(&format!("                {outcome}::Denied {{ reason: reason.clone() }}\n"));
        s.push_str("            }\n");
    }

    s.push_str("            vesl_core::PokeOutcome::Rejected {\n");
    s.push_str("                reason: vesl_core::RejectionReason::Unknown\n");
    s.push_str("                    | vesl_core::RejectionReason::RbacDenied { .. },\n");
    s.push_str(&format!("            }} => {outcome}::Unknown,\n"));
    s.push_str(&format!(
        "            vesl_core::PokeOutcome::Crashed {{ .. }} => {outcome}::Crashed,\n",
    ));
    // Fallthrough catches: KernelError/KernelRejected/GateDenied whose
    // cord/tag didn't match this graft — they belong to a different
    // graft's namespace.
    s.push_str(&format!("            _ => {outcome}::Unknown,\n"));
    s.push_str("        }\n");
    s.push_str("    }\n");
    s.push_str("}\n\n");
}

fn graft_has_typed_outcome(graft: &HarnessGraftBindings) -> bool {
    !graft.errors.is_empty() || !graft.rejected.is_empty() || !graft.denied.is_empty()
}

/// Walk every arg's rust-type string and figure out which `use` lines
/// the generated file needs. Known non-primitive idents:
/// `Tip5Hash`, `ValidateRule`, `ProofNode`, `NounSlab`.
fn collect_used_types(loaded: &LoadedHarnessBindings) -> Vec<&'static str> {
    let candidates = ["Tip5Hash", "ValidateRule", "ProofNode", "NounSlab"];
    let mut out: Vec<&'static str> = Vec::new();
    for graft in &loaded.bindings.grafts {
        for poke in &graft.pokes {
            for arg in &poke.args {
                for cand in &candidates {
                    if arg.rust.contains(cand) && !out.contains(cand) {
                        out.push(*cand);
                    }
                }
            }
        }
        for rej in &graft.rejected {
            for field in &rej.fields {
                for cand in &candidates {
                    if field.rust.contains(cand) && !out.contains(cand) {
                        out.push(*cand);
                    }
                }
            }
        }
    }
    out.sort();
    out
}

fn render_use_line(ident: &str) -> String {
    match ident {
        "Tip5Hash" | "ValidateRule" | "ProofNode" => {
            format!("use vesl_core::{ident};\n")
        }
        "NounSlab" => "use nock_noun_rs::NounSlab;\n".to_string(),
        _ => String::new(),
    }
}

/// `counter-set` → `CounterSet`, `settle-register-rejected` →
/// `SettleRegisterRejected`. Splits on `-`, capitalizes each segment.
fn pascal_case(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for word in s.split('-') {
        let mut chars = word.chars();
        if let Some(c) = chars.next() {
            out.extend(c.to_uppercase());
        }
        for c in chars {
            out.push(c);
        }
    }
    out
}

/// Strip a leading `<graft>-` prefix from a tag. `settle-register-rejected`
/// against graft `settle` becomes `register-rejected`. Leaves unmatched
/// tags untouched so the resulting variant name is always something.
fn strip_graft_prefix<'a>(tag: &'a str, graft_name: &str) -> &'a str {
    let prefix = format!("{graft_name}-");
    tag.strip_prefix(&prefix).unwrap_or(tag)
}

/// Default value for a Rust type, used when constructing typed rejection
/// variants whose field decoding is deferred to v2.0. Conservative:
/// returns `String::new()`, `0`, `Vec::new()` for the common shapes; an
/// unrecognized type falls back to `Default::default()` which compiles
/// for any `Default`-bound type and fails loudly for one that isn't.
fn default_value_for(rust: &str) -> &'static str {
    let t = rust.trim();
    match t {
        "String" => "String::new()",
        "u64" | "u32" | "u16" | "u8" => "0",
        "Vec<u8>" => "Vec::new()",
        _ => "Default::default()",
    }
}
